version: '3'

services:
  # PHP service
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/symfony:rw
    depends_on:
      - database

  # MySQL service
  database:
    image: mysql:8.0
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
